# 3 Pandas tricks every Data Scientist should know

If you are new to the world of data science, Python's Pandas libraries are some of the best tools for quick data analysis. Pandas are built on Numpy, another popular Python libary. The purpose of this tutorial is to provide 3 tips and tricks with plenty of practice examples that should be part of your tool kit as a Data Scientist. 

You will use data from one of the most infamous shipwrecks, the sinking of the RMS Titanic. You've almost certainly heard stories about the sinking of the Titanic in 1912 when it hit an iceberg on its maiden voyage. Astonishingly, there were not enough lifeboats available for all the passengers. This tragic tale got even more interesting and personal when I found out that one of my friend's great-grandfather was on the Titanic. It get's worse - he was the helmsman! Two facts that most people seem to remember are.
1. The women were given preference to the lifeboats over the men and as a result many more survived.
2. Those in first class were given access to the lifeboats over those in other classes.

In this tutorial you will have access to a subset of the data and confirm these facts for yourself. 

<img src="titanic.JPG">

<i>By Unknown photographer, photo taken on April 11, 1912 - Cobh Heritage Centre, Ireland, <a href="http://www.cobhheritage.com/welcome/cobh-heritage-centre/">http://www.cobhheritage.com/welcome/cobh-heritage-centre/</a></i>

The Kaggle team have generously provided two data sets to perform some machine learning tasks. (https://www.kaggle.com/c/titanic/data) For the purposes of this tutorial we will only use one of them and so we will only work with a partial dataset for the passenger list on the Titanic.

Let's get started!

In [2]:
import pandas as pd
import numpy as np

tt = pd.read_csv("titanic.csv")

Before you start on any of the Panda tools, you will want to examine the dataframe to get an overview of your dataset. 

In [3]:
# You will notice straight away that although the data set has 891 entries, you have missing values for Age, Cabin 
# and Embarked. 
tt.info()
tt.head(6)
#tt.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q

# #1 Boolean Indexing
This disaster is famous as women were given preference to the limited number of lifeboats, with many men giving up their places. Can you confirm this is the case with this data set? Boolean Indexing allows you to filter based on a series of conditions. Comparing the number of male and female survivors with the total proportion for both, the data certainly seems to suggest that the survival rate for women (0.4) was more than double that for men (0.19). 

Remember that the separate Pandas conditions need to be in brackets and you will use '&' and '|' to combine conditions (a series of boolean values). You can also format the output of "Survival rate" using the round() function.

Want to find out more about Boolean Indexing? (http://pandas.pydata.org/pandas-docs/stable/indexing.html#boolean-indexing)

In [4]:
print("Sex           :","Male","Female")
print("Survivors     :",len(tt[(tt["Survived"] == 1) & (tt["Sex"] == "male")]), \
len(tt[(tt["Survived"] == 1) & (tt["Sex"] == "female")]))
print("Total         :",len(tt[tt["Sex"] == "male"]), len(tt[tt["Sex"] == "female"]))
print("Survival rate :",round(len(tt[(tt["Survived"] == 1) & (tt["Sex"] == "male")]) / \
                              len(tt[tt["Sex"] == "male"]),2), \
      round(len(tt[(tt["Survived"] == 1) & (tt["Sex"] == "female")]) / len(tt[tt["Sex"] == "male"]),2))



Sex           : Male Female
Survivors     : 109 233
Total         : 577 314
Survival rate : 0.19 0.4


Shockingly, there are also tales that travellers with first class tickets were given preference to the lifeboats than those with third class tickets. Assume that you will only check what class the traveller is in, and not whether they are also male or female. Can you confirm if the data suggests this was the case?  The expected output is given below. Can you modify the code below to confirm this?

In [5]:
# The basic framework has been provided. Modify only this cell and confirm you can get the Expected output below. 
# Remember to use tt.info() / tt.head() above if you want to have an overview of the structure of the data.

print("Class of travel :","1st","2nd","3rd")
print("Survivors       :",len(tt[(tt["Survived"] == 1) & (tt["Pclass"] == 1)])," - "," - ")
print("Total           :"," - "," - ",len(tt[tt["Pclass"] == 3]))
print("Survival rate   :"," - ", \
      round(len(tt[(tt["Survived"] == 1) & (tt["Pclass"] == 2)]) / len(tt[tt["Pclass"] == 2]),2)," - ")



Class of travel : 1st 2nd 3rd
Survivors       : 136  -   - 
Total           :  -   -  491
Survival rate   :  -  0.47  - 


# #2 Dealing with missing values
If you remember from the first part of this tutorial, although we had 891 entries, Age, Cabin and Embarked all had some null values. There are a couple of ways you can deal with this.

## 2.1 Drop the missing values.
We can use Panda's dropna().

tt.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

This will drop any rows with missing values. Clearly this isn't a good idea in this instance because we will reduce the number of passengers in our data set from 891 to 183. Fortunately, Pandas doesn't make any of the changes to your dataframe object until you change the inplace=False flag to True.

What instead if we wanted to remove any columns with missing values?  Modify the code in the line below. The original dataset has 12 columns. As Age, Cabin and Embarked all have null values, you should end up with only 9 columns.


In [6]:
# Modify the line below to remove any columns with missing values
# tt.dropna()
# Modify the line below to set a threshold of 11 non-null values for a row.
# tt.dropna()

Another option that you have is to set a threshold. So, for example, you can specify that if 11 of a row's 12 fields has a non-null value, you won't drop that row. You are now left with 733 entries from the original 891 - a definite improvement on 183 with dropping any rows with missing values. Modify the line above to confirm this is the case. Dropping missing values isn't a good option here. Let's try another of Panda's options, filling the missing values.

## 2.2 Filling the missing values
There are many statistical schools of thought on what missing or null values should be replaced with. You already know from tt.describe() that the average(mean) age is 29.69. You can see that the 6th, 18th and 20th entry below have missing values replaced. 

In [7]:
# The mean
tt["Age"].fillna(value=29.69)
# The median - complete the following line to fill in the missing values with the median age
# tt["Age"].fillna(value=

0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
5      29.69
6      54.00
7       2.00
8      27.00
9      14.00
10      4.00
11     58.00
12     20.00
13     39.00
14     14.00
15     55.00
16      2.00
17     29.69
18     31.00
19     29.69
20     35.00
21     34.00
22     15.00
23     28.00
24      8.00
25     38.00
26     29.69
27     19.00
28     29.69
29     29.69
       ...  
861    21.00
862    48.00
863    29.69
864    24.00
865    42.00
866    27.00
867    31.00
868    29.69
869     4.00
870    26.00
871    47.00
872    33.00
873    47.00
874    28.00
875    15.00
876    20.00
877    19.00
878    29.69
879    56.00
880    25.00
881    33.00
882    22.00
883    28.00
884    25.00
885    39.00
886    27.00
887    19.00
888    29.69
889    26.00
890    32.00
Name: Age, dtype: float64

The median is another good value that we could use. Modify the code above to use the median. 
(Hint : use tt["Age"].median() to help. You should find null values replaced with the median of 28.0)

# #3 The Apply function
This is one of the most powerful tools available in Pandas. Apply, allows you to either use built in functions or to create your own custom function and then run it on an entire column. What would have been the price of the tickets on the Titanic in today's money? Taking into account inflation, prices have increased by about 106 times. Apply functions can be particularly powerful when we combine them with lambda expressions. 
What is the simple lambda expression you need to create to determine the fares in today's money?
Can you determine what would have been the most expensive ticket in today's money? You should get 54306.90.

Try it out in the one-liners below.

In [8]:
# Updating the fares for all the passengers
#tt["Fare"].apply(lambda x : 106 * x)
# How can you modify the line below to show the highest fare?
#tt["Fare"].apply(lambda x : 106 * x).

The Titanic set off from Southampton, stopping off at Cherbourg and Queenstown. 

<img src="route.GIF">
<i>Source : http://www.titanicfacts.net/titanic-maiden-voyage.html</i>

I don't know about you, but I always struggle with remembering the names of French towns and ports. To help me out, I've written a function, get_full_name(),  that converts the one letter code of the Embarked column to its full name, for all the towns, French or otherwise . Using Panda's apply function, I can then run this throughout the entire column as shown below.  

Want to find out more about the Apply function. http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html#pandas.DataFrame.apply

In [9]:
def get_full_name(x):
    if (x == "S"):
        return "Southampton"
    elif ( x == "C"):
        return "Cherbourg"
    elif ( x == "Q"):
        return "Queenstown"

tt["Embarked"].apply(get_full_name)        

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
5       Queenstown
6      Southampton
7      Southampton
8      Southampton
9        Cherbourg
10     Southampton
11     Southampton
12     Southampton
13     Southampton
14     Southampton
15     Southampton
16      Queenstown
17     Southampton
18     Southampton
19       Cherbourg
20     Southampton
21     Southampton
22      Queenstown
23     Southampton
24     Southampton
25     Southampton
26       Cherbourg
27     Southampton
28      Queenstown
29     Southampton
          ...     
861    Southampton
862    Southampton
863    Southampton
864    Southampton
865    Southampton
866      Cherbourg
867    Southampton
868    Southampton
869    Southampton
870    Southampton
871    Southampton
872    Southampton
873    Southampton
874      Cherbourg
875      Cherbourg
876    Southampton
877    Southampton
878    Southampton
879      Cherbourg
880    Southampton
881    Southampton
882    South

I hope you have had fun exploring this data set. These are the top 3 Panda tips I recommend every Data Scientist has in their tool kit. Let me know in the comments section below if you think another Panda tool should have made the list.